gerencial/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'clients#index'
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

gerencial/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

gerencial/app/models/client.rb
class Client < ApplicationRecord
end

gerencial/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

gerencial/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

gerencial/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:nome, :conta, :senha, :email, :mensagem)
    end
end

gerencial/app/helpers/application_helper.rb
module ApplicationHelper
end

gerencial/app/helpers/clients_helper.rb
module ClientsHelper
end

gerencial/app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :conta %>
    <%= form.number_field :conta %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mensagem %>
    <%= form.text_field :mensagem %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gerencial/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

gerencial/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
  <li class="menu-item sign-out">
    <%= link_to("Sign Out", "/users/sign_out", method: :delete) %>
  </li>
<% else %>
  <li class="menu-item sign-in">
    <%= link_to("Sign In", "/users/sign_in") %>
  </li>
  <li class="menu-item sign-up">
    <%= link_to("Sign Up", "/users/sign_up") %>
  </li>
<% end %>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Conta</th>
      <th>Senha</th>
      <th>Email</th>
      <th>Mensagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.nome %></td>
        <td><%= client.conta %></td>
        <td><%= client.senha %></td>
        <td><%= client.email %></td>
        <td><%= client.mensagem %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

gerencial/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

gerencial/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @client.nome %>
</p>

<p>
  <strong>Conta:</strong>
  <%= @client.conta %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @client.senha %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Mensagem:</strong>
  <%= @client.mensagem %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

gerencial/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerencial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>